# Generated by Django 5.1.3 on 2025-04-22 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(blank=True, max_length=250, verbose_name='First Name')),
                ('l_name', models.CharField(blank=True, max_length=250, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=250, verbose_name='Email Address')),
                ('phone', models.PositiveIntegerField(blank=True, verbose_name='Phone Number')),
                ('ticket_type', models.CharField(blank=True, max_length=250, verbose_name='Ticket Type')),
                ('row', models.CharField(blank=True, max_length=250, verbose_name='Row')),
                ('seat', models.PositiveIntegerField(blank=True, verbose_name='Seat')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_details', to='order.order')),
            ],
        ),
    ]
